server:
  address: 0.0.0.0
  port: 443
  ssl:
    enabled: true
    key-store: /opt/turbulencehub/keystore.p12
    key-store-password: abhay
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  application:
    name: spring_example
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: abhay
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
